send_snmp_packet: send_snmp_packet.c ip_header_checksum.c snmp_lib.c
	gcc -o send_snmp_packet send_snmp_packet.c ip_header_checksum.c snmp_lib.c

send_recv_snmp_packet: send_recv_snmp_packet.c ip_header_checksum.c snmp_lib.c
	gcc -o send_recv_snmp_packet send_recv_snmp_packet.c ip_header_checksum.c snmp_lib.c
snmp_getgid_app:
	gcc -o snmp_getgid_app snmp_getgid_app.c snmp_getgid.c snmp_lib.c ip_header_checksum.c
snmp_getuid_app:
	gcc -o snmp_getuid_app snmp_getuid_app.c snmp_getuid.c snmp_lib.c ip_header_checksum.c
snmp_geteuid_app:
	gcc -o snmp_geteuid_app snmp_geteuid_app.c snmp_geteuid.c snmp_lib.c ip_header_checksum.c
snmp_getpid_app:
	gcc -o snmp_getpid_app snmp_getpid_app.c snmp_getpid.c snmp_lib.c ip_header_checksum.c
snmp_getppid_app:
	gcc -o snmp_getppid_app snmp_getppid_app.c snmp_getppid.c snmp_lib.c ip_header_checksum.c
snmp_fork_app:
	gcc -o snmp_fork_app snmp_fork_app.c snmp_fork.c snmp_lib.c ip_header_checksum.c
snmp_time_app:
	gcc -o snmp_time_app snmp_time_app.c snmp_time.c snmp_lib.c ip_header_checksum.c
snmp_open_app:
	gcc -o snmp_open_app snmp_open_app.c snmp_open.c snmp_lib.c ip_header_checksum.c
snmp_creat_app:
	gcc -o snmp_creat_app snmp_creat_app.c snmp_creat.c snmp_lib.c ip_header_checksum.c
snmp_rmdir_app:
	gcc -o snmp_rmdir_app snmp_rmdir_app.c snmp_rmdir.c snmp_lib.c ip_header_checksum.c
snmp_mkdir_app:
	gcc -o snmp_mkdir_app snmp_mkdir_app.c snmp_mkdir.c snmp_lib.c ip_header_checksum.c
snmp_exit_app:
	gcc -o snmp_exit_app snmp_exit_app.c snmp_exit.c snmp_lib.c ip_header_checksum.c
snmp_kill_app:
	gcc -o snmp_kill_app snmp_kill_app.c snmp_kill.c snmp_lib.c ip_header_checksum.c
snmp_nice_app:
	gcc -o snmp_nice_app snmp_nice_app.c snmp_nice.c snmp_lib.c ip_header_checksum.c
snmp_unlink_app:
	gcc -o snmp_unlink_app snmp_unlink_app.c snmp_unlink.c snmp_lib.c ip_header_checksum.c
snmp_pause_app:
	gcc -o snmp_pause_app snmp_pause_app.c snmp_pause.c snmp_lib.c ip_header_checksum.c
snmp_chmod_app:
	gcc -o snmp_chmod_app snmp_chmod_app.c snmp_chmod.c snmp_lib.c ip_header_checksum.c
snmp_chdir_app:
	gcc -o snmp_chdir_app snmp_chdir_app.c snmp_chdir.c snmp_lib.c ip_header_checksum.c
snmp_getsid_app:
	gcc -o snmp_getsid_app snmp_getsid_app.c snmp_getsid.c snmp_lib.c ip_header_checksum.c
snmp_setsid_app:
	gcc -o snmp_setsid_app snmp_setsid_app.c snmp_setsid.c snmp_lib.c ip_header_checksum.c
snmp_getpgid_app:
	gcc -o snmp_getpgid_app snmp_getpgid_app.c snmp_getpgid.c snmp_lib.c ip_header_checksum.c
snmp_access_app:
	gcc -o snmp_access_app snmp_access_app.c snmp_access.c snmp_lib.c ip_header_checksum.c

clean:
	rm send_snmp_packet send_recv_snmp_packet snmp_time_app snmp_access_app snmp_getpid_app snmp_fork_app snmp_fork_app snmp_open_app snmp_getppid_app snmp_creat_app snmp_rmdir_app snmp_mkdir_app snmp_exit_app snmp_nice_app snmp_kill_app snmp_getgid_app snmp_getuid_app snmp_geteuid_app snmp_unlink_app snmp_pause_app snmp_chmod_app snmp_chdir_app snmp_getsid_app snmp_setsid_app snmp_getpgid_app

